### ISSUE TITLE
Client crash with nickname

### ISSUE THREAD

**Issue by Flame115** [John-Paul-R/Essential-Commands#91] opened 2022-01-19 06:24 UTC
when i type /nickname set (my user) "red" my game crashes, it crashes when you type the last ", not when you send it but when you type it. here is the crash log 

https://pastebin.com/1cF0XtwG

**Comment by John-Paul-R** [comment] 2022-01-20 03:09
>	at io.github.**darkkronicle.advancedchatbox**.formatter.CommandColorer.fromRange(CommandColorer.java:167)

> darkkronicle.advancedchatbox

sus

---

I'll see if there is anything I can do on my end, though I'd hazard a guess that this might be an `advancedchatbox` thing.

**Comment by John-Paul-R** [comment] 2022-01-20 03:18
Yeah, this seems to be their json or text parser. I can reproduce this with tellraw: `/tellraw @p "testing"` -> crash. Will make an issue on their GitHub.

**Comment by John-Paul-R** [comment] 2022-01-20 03:29
Actually, since this seems to be wholly a problem from AdvancedChatBox, I'm going to close this issue here. Not much do be done by EC unfortunately.

If you're just looking to set a nickname and don't want to get rid of AdvancedChatBox, using the Placeholders format should work:

eg: `<red>MyNameInRed</red>`

**Closed as completed by John-Paul-R** 2022-01-20 03:29 UTC
Labels: mod incompat
