### ISSUE TITLE
Anti-Virus being tripped

### ISSUE THREAD

**Issue by Lunaticol** [John-Paul-R/Essential-Commands#291] opened 2024-07-01 16:28 UTC
Having a friends anti-virus get tripped from the mod. Says it contains a trojan. Nothing trips from my end. They are using Bitdefender 
![image](https://github.com/John-Paul-R/Essential-Commands/assets/91378087/faf2be91-79fd-42b7-8a50-3165d9b31676)

**Comment by arnokeesman** [comment] 2024-07-01 16:37
Duplicate of #276

**Comment by John-Paul-R** [comment] 2024-07-16 03:35
Yeah, going to track all the AV fun under #276. Thanks for the report!

**Closed as completed by John-Paul-R** 2024-07-16 03:35 UTC
