### ISSUE TITLE
luckperms is not recognizing essential Commands,

### ISSUE THREAD

**Issue by thasic9** [John-Paul-R/Essential-Commands#82] opened 2021-12-11 21:18 UTC
cant add any perms with luckperms, its not recognizing essential commands.

**Comment by John-Paul-R** [comment] 2021-12-11 21:57
What version of mc and essential commands are you running?

Do you have `use_permissions_api` set to `true` in `config/EssentialCommands.properties`?

A log file (located at `logs/latest.log`), uploaded to a site like https://hatebin.com and linked here would provide a lot of much needed (and currently missing) information.

**Comment by Flame115** [comment] 2021-12-24 06:40
It's also not being recognized for me either, do you still want the log?

**Comment by John-Paul-R** [comment] 2021-12-24 16:27
Yes, the content of `logs/latest.log` and `config/EssentialCommands.json` would help in identifying the cause of the issue.

**Comment by Flame115** [comment] 2021-12-24 19:04
Interesting, it seems that now none of the perms show up, not just essential commands.

well, here are the logs anyways:

Log: https://pastebin.com/y5kjBFsk

Config: https://pastebin.com/fe1uJxXu

**Comment by John-Paul-R** [comment] 2021-12-25 20:36
Upon rereading what is happening here, I think this may be a duplicate of #56 (Which I unfortunately am not sure how to solve, nor do I know the cause :/).

@Flame115 @thasic9 If you grant the permissions using LuckPerms commands instead of through their gui, do things work as expected?

ex:
```
/lp user <user-name> permission set essentialcommands.fly.self
```

Should grant the specified user access to the `/fly` command (for self only). (Despite the fact that LuckPerms does not auto-suggest the permissions.)

If this does not work, I'm not quite sure what is causing this at present...

**Comment by Flame115** [comment] 2021-12-26 00:23
yes, using the command does seem to work. it was successfully added. hmm

**Comment by John-Paul-R** [comment] 2022-07-23 01:34
Closing as duplicate of #56

**Closed as not planned by John-Paul-R** 2022-07-23 01:34 UTC
Labels: bug

**Comment by Sheendrah** [comment] 2024-04-18 11:11
> Do you have use_permissions_api set to true in config/EssentialCommands.properties?

You save my life Man ! THANK YOU !
