### ISSUE TITLE
persist /back to storage

### ISSUE THREAD

**Issue by TecEash1** [John-Paul-R/Essential-Commands#146] opened 2022-10-05 18:50 UTC
After I restart my server I can no longer run /back, can you please fix that and make the last location of the player be stored somewhere so that it works, it works in essentials like this I believe

**Comment by John-Paul-R** [comment] 2022-10-08 14:37
duplicate of #69

**Closed as completed by John-Paul-R** 2022-10-08 14:37 UTC

**Comment by TecEash1** [comment] 2022-10-08 14:39
Sorry about that, I didn't see that

**Comment by John-Paul-R** [comment] 2022-10-08 14:48
np!
